name: rpc
version: 0.6.2
description: Library for exposing Dart server-side APIs.
homepage: https://github.com/dart-lang/rpc

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
  args: ^2.3.1
  collection: '>=1.1.1 <2.0.0'
  convert: ^3.0.2
  crypto: ^3.0.2
  discoveryapis_generator: ^1.0.0
  gcloud: ^0.8.5
  http_parser: ^4.0.1
  logging: ^1.0.2
  mime: ^1.0.0
  path: '>=1.3.4 <2.0.0'
  uri: ^1.0.0

dev_dependencies:
  test: ^1.2.0
